// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_id,
    first_name,
    last_name,
    email,
    phone,
    age,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING user_id, email, status
`

type CreateUserParams struct {
	UserID    pgtype.UUID
	FirstName string
	LastName  string
	Email     string
	Phone     string
	Age       int32
	Status    int32
}

type CreateUserRow struct {
	UserID pgtype.UUID
	Email  string
	Status int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Age,
		arg.Status,
	)
	var i CreateUserRow
	err := row.Scan(&i.UserID, &i.Email, &i.Status)
	return i, err
}
